Add limit reach error
gfish/genderize_io_rb pull request #1
Opened 2016-12-22 16:33 UTC by guandai

Need a error to indicate Request limit reached

2016-12-23 11:11 UTC, guandai commented
@nj  Can I just merge this PR , as I need it for continue development

2016-12-25 09:56 UTC, nj requested changes
`LimitReach` > `LimitReached`

2016-12-27 21:41 UTC, nj requested changes
Also specs seems to be missing in regards to this which might block the changes in getting back to the upstream.

2016-12-27 21:41 UTC, nj commented on lib/genderize_io_rb.rb
> +          raise GenderizeIoRb::Errors::LimitReached.new(json_result[1]) if json_result.include? "limit too low"
If Rubocop had been included in this project, it would have lead to a [RaiseArgs](http://www.rubydoc.info/gems/rubocop/0.44.0/RuboCop/Cop/Style/RaiseArgs) offences. Better have it corrected.

2016-12-27 22:34 UTC, guandai commented on lib/genderize_io_rb.rb
> +          raise GenderizeIoRb::Errors::LimitReached.new(json_result[1]) if json_result.include? "limit too low"
Updated in 	0dfb828
Spec added in 	3e0af29

2016-12-28 14:52 UTC, nj commented on lib/genderize_io_rb.rb
> +            error = GenderizeIoRb::Errors::NameNotFound, "Name was not found on Genderize.io: '#{json_result["name"]}'."
Think you've breaked the code here, as it's not a raise... Not sure why it's made this way in the first place.

2016-12-28 14:52 UTC, nj commented on spec/genderize_io_rb_spec.rb
> +    JSON.stub(:parse) { "limit too low" }
Would have been better to stub the `http`-request itself instead of this. Also seems like the other raise spec got the same bad practise with calling remote when not needed.

2016-12-28 18:15 UTC, guandai commented
I close this PR , because it is from my account repo,   and I would like to move the code to extend_api branch too

2016-12-28 18:15 UTC, closed without merging